// All icons: node_modules/@fortawesome/free-solid-svg-icons/index.d.ts
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faCaretLeft,
  faCaretRight,
  faCaretUp,
  faCaretDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDown,
  faCircleQuestion,
  faCartShopping,
  faMagnifyingGlass,
  faLaptop,
  faDesktop,
  faMobile,
  faList,
  faRobot,
  faChartLine,
  faPaintBrush,
  faCheck,
  faPencil,
  faHouseChimney,
  faCheckSquare,
  faCheckCircle,
  faExclamationCircle,
  faExclamationTriangle,
  faMagnifyingGlassPlus,
  faMagnifyingGlassMinus,
  faMaximize,
  faCircleUp,
  faCircleUser,
  faUser,
  faRightFromBracket,
  faArrowRightFromBracket,
  faReply,
  faShare,
  faXmark,
  faGear,
  faEye,
  faUpload,
  faCircleInfo,
  faMinus,
  faPlus,
  faUpRightFromSquare,
  faRightLeft,
  faLightbulb,
  faCloud,
  faLink,
  faBars,
  faMessage,
  faShareNodes,
  faRefresh,
  faCirclePlus,
  faFileImport,
  faEnvelope,
  faLanguage,
} from '@fortawesome/free-solid-svg-icons'
import {
  faTrashCan as farTrashCan,
  faCircleQuestion as farCircleQuestion,
  faStar as farStar,
  faRectangleList as farRectangleList,
  faCalendar as farCalendar,
  faImage as farImage,
  faSquarePlus as farSquarePlus,
  faFileImage as farFileImage,
  faFolder as farFolder,
} from '@fortawesome/free-regular-svg-icons'

// import { faTwitter, faFontAwesome } from '@fortawesome/free-brands-svg-icons'

library.add(
  // solid here ↓
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faCaretLeft,
  faCaretRight,
  faCaretUp,
  faCaretDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDown,
  faCircleQuestion,
  faCartShopping,
  faMagnifyingGlass,
  faLaptop,
  faDesktop,
  faMobile,
  faList,
  faRobot,
  faChartLine,
  faPaintBrush,
  faCheck,
  faCheckSquare,
  faPencil,
  faHouseChimney,
  faCheckCircle,
  faExclamationCircle,
  faExclamationTriangle,
  faMagnifyingGlassPlus,
  faMagnifyingGlassMinus,
  faMaximize,
  faCircleUp,
  faCircleUser,
  faUser,
  faRightFromBracket,
  faArrowRightFromBracket,
  faReply,
  faShare,
  faXmark,
  faGear,
  faEye,
  faUpload,
  faCircleInfo,
  faMinus,
  faPlus,
  faUpRightFromSquare,
  faRightLeft,
  faLightbulb,
  faCloud,
  faLink,
  faBars,
  faMessage,
  faShareNodes,
  faRefresh,
  faCirclePlus,
  faFileImport,
  faEnvelope,
  faLanguage,

  // Regular here ↓
  farCircleQuestion,
  farTrashCan,
  farStar,
  farRectangleList,
  farCalendar,
  farImage,
  farSquarePlus,
  farFileImage,
  farFolder,
)