/*
import all the base items as:
import { BButton, BInput, ... } from "client/components/base/index"
*/
export { BHeading, BText } from "./Typography"
export { BIcon } from "./Icon"
export { BButton } from "./Button"
export { BSpinner } from "./Spinner"
export { BLink } from "./Link"
export { BTab } from "./Tab"
export { BLabel } from "./Label"
export { BInput } from "./Input"
export { BQuantity } from "./Quantity"
export { BSearch } from "./Search"
export { BTextarea } from "./Textarea"
export { BSelect } from "./Select"
export { BCheckbox } from "./Checkbox"
export { BSwitch } from "./Switch"
export { BRadio } from "./Radio"
export { BAlert } from "./Alert"
export { BModal } from "./Modal"
export { BTable, BThead, BTbody, BTr, BTh, BTd } from "./Table"
export { BPagination } from "./Pagination"
export { BLoading } from "./Loading"
export { BFile } from "./File"
export { BSlider } from "./Slider"